# Generated by Django 4.2.7 on 2024-01-15 09:27

from django.db import migrations, models
import talent_reserves.yandex_s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnews',
            name='image',
            field=models.ImageField(storage=talent_reserves.yandex_s3_storage.ClientDocsStorage(), upload_to='photo_news/'),
        ),
    ]
