# Generated by Django 4.2.7 on 2023-11-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnews',
            name='image',
            field=models.ImageField(upload_to='photos_news/'),
        ),
        migrations.AlterField(
            model_name='contentnews',
            name='title_photo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
