# Generated by Django 4.2.7 on 2023-12-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagnews',
            options={'verbose_name': 'tag news', 'verbose_name_plural': 'tag news'},
        ),
    ]
