# Generated by Django 4.2.7 on 2023-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_contentnews_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnews',
            name='image',
            field=models.ImageField(upload_to='photo_news/'),
        ),
    ]
