# Generated by Django 4.2.7 on 2024-03-27 17:11

from django.db import migrations, models
import talent_reserves.yandex_s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_contentnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnews',
            name='image',
            field=models.ImageField(storage=talent_reserves.yandex_s3_storage.ClientMediaStorage(), upload_to='photo_news/'),
        ),
    ]
