# Generated by Django 4.2.7 on 2024-03-27 17:11

from django.db import migrations, models
import talent_reserves.yandex_s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='image',
            field=models.ImageField(blank=True, storage=talent_reserves.yandex_s3_storage.ClientMediaStorage(), upload_to='posts/'),
        ),
    ]
